--1.CREATING THE PLAGABLE DATABASE
CREATE PLUGGABLE DATABASE hu_pdb_28751
  2  ADMIN USER admin IDENTIFIED BY 12345
  3  FILE_NAME_CONVERT =( 'D:\Oracle21\oradata\ORCL\pdbseed','D:\MY_PDB' );

--OPENING THE PLAGABLE DATABASE
ALTER PLUGGABLE DATABASE hu_pdb_28751 OPEN;

--CREATING THE USER
--first you alter the session
ALTER SESSION SET CONTAINER = hu_pdb_28751;
--then you create the user
CREATE USER hugues_plsqlauca_28751 IDENTIFIED BY 12345;

--2.CREATING PLUGGABLE DATABASE TO DELETE
CREATE PLUGGABLE DATABASE hu_to_delete_pdb_28751
ADMIN USER admin IDENTIFIED BY 12345;

--DELETING PLUGGABLE DATABASE TO DELETE
--you have to delete a PDB when you are in the CDB container then delete
ALTER SESSION SET CONTAINER =CDB$ROOT;
DROP PLUGGABLE DATABASE hu_to_delete_pdb_28751 INCLUDING DATAFILES;


